// Code generated by sqlc. DO NOT EDIT.

package pg

import (
	"database/sql"
	"time"
)

type Item struct {
	ID        int64
	Name      string
	Source    string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type List struct {
	ID        int64
	Name      string
	UserID    int64
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type ListHeart struct {
	ID        int64
	ListID    int64
	UserID    int64
	CreatedAt time.Time
	DeletedAt sql.NullTime
}

type ListItem struct {
	ID        int64
	Quantity  sql.NullInt64
	Collected bool
	ListID    int64
	ItemID    int64
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type User struct {
	ID             int64
	Name           string
	Email          string
	HashedPassword []byte
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
}
