// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pg "github.com/leggettc18/grindlists/api/pg"
)

// ListItemResolver is an autogenerated mock type for the ListItemResolver type
type ListItemResolver struct {
	mock.Mock
}

// Item provides a mock function with given fields: ctx, obj
func (_m *ListItemResolver) Item(ctx context.Context, obj *pg.ListItem) (*pg.Item, error) {
	ret := _m.Called(ctx, obj)

	var r0 *pg.Item
	if rf, ok := ret.Get(0).(func(context.Context, *pg.ListItem) *pg.Item); ok {
		r0 = rf(ctx, obj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pg.Item)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pg.ListItem) error); ok {
		r1 = rf(ctx, obj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Quantity provides a mock function with given fields: ctx, obj
func (_m *ListItemResolver) Quantity(ctx context.Context, obj *pg.ListItem) (*int, error) {
	ret := _m.Called(ctx, obj)

	var r0 *int
	if rf, ok := ret.Get(0).(func(context.Context, *pg.ListItem) *int); ok {
		r0 = rf(ctx, obj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pg.ListItem) error); ok {
		r1 = rf(ctx, obj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
