// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen

type ItemInput struct {
	Name   string `json:"name"`
	Source string `json:"source"`
}

type ListInput struct {
	Name   string `json:"name"`
	UserID int64  `json:"user_id"`
}

type ListItemInput struct {
	Quantity  *int  `json:"quantity"`
	Collected bool  `json:"collected"`
	ListID    int64 `json:"list_id"`
	ItemID    int64 `json:"item_id"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
